apiVersion: v1
kind: Config

clusters:
- cluster:
    certificate-authority: ca.crt
    server: https://my-play:6446
  name: my-play

users:
- name: my-kube-admin
  user:
    client-certificate: admin.crt
    client-key: admin.key
contexts:
- context:
    user: my-kube-admin
    cluster: my-play
    namespace: my-ns
  name: my-kube-admin@my-play


# kubectl config --kubeconfig=config-demo set-cluster development --server=https://1.2.3.4 --certificate-authority=fake-ca-file
# kubectl config --kubeconfig=config-demo set-credentials developer --client-certificate=fake-cert-file --client-key=fake-key-seefile
# kubectl config --kubeconfig=config-demo set-context dev-frontend --cluster=development --namespace=frontend --user=developer
# kubectl config --kubeconfig=config-demo view
# kubectl --kubeconfig=config-demo config unset contexts.<name> 
# clusters.<name> users.<name>
# k config use-context my-kube-admin@my-play



# vi ~/.bashrc

# Add one of these lines to export the variable:
# export KUBECONFIG=/root/my-kube-config
# # OR
# export KUBECONFIG=~/my-kube-config
# # OR
# export KUBECONFIG=$HOME/my-kube-config

# Apply the Changes:

# Reload the shell configuration to apply the changes in the current session:

# source ~/.bashrc