# k create secret generic app-secret --from-literal=DB_Host=mysql --from-literal=DB_User=root --from-literal=DB_password=paswrd
# --from-file=app-secret.properties

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: mysql
  DB_User: root
  DB_password: paswrd


# apiVersion: v1
# kind: Pod
# metadata:
#   name: secret-demo-pod
# spec:
#   containers:
#     - name: demo
#       image: alpine
#       command: ["sleep", "3600"]
#        envFrom:
#           - secretRef:
#                name: app-secret

# k -n webhook-demo create secret tls webhook-server-tls --cert "/root/keys/webhook-server-tls.crt" --key "/root/keys/webhook-server-tls.key"